# For more information: https://laravel.com/docs/sail
version: '3'
services:
    nginx:
        build:
            context: .
            dockerfile: docker/prod/nginx/Dockerfile
        ports:
            - "127.0.0.1:${NGINX_PORT}:80"
        volumes:
          - './storage:/var/www/html/storage'
        environment:
            TZ: Asia/Taipei
        networks:
            - internal
        restart: unless-stopped
    php:
        build:
            context: .
            dockerfile: docker/prod/php-fpm/Dockerfile
        volumes:
          - './storage:/var/www/html/storage'
        environment:
            TZ: Asia/Taipei
        networks:
            - internal
        restart: unless-stopped
    db:
        image: 'mariadb:10.8.3'
        # ports:
        # - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ROOT_HOST: "%"
            MARIADB_DATABASE: '${DB_DATABASE}'
            MARIADB_USER: '${DB_USERNAME}'
            MARIADB_PASSWORD: '${DB_PASSWORD}'
            MARIADB_ALLOW_EMPTY_PASSWORD: 1
            TZ: Asia/Taipei
        volumes:
            - 'db:/var/lib/mysql'
        networks:
            - internal
        restart: unless-stopped

networks:
    internal:
        driver: bridge

volumes:
    db:
        driver: local
    redis:
        driver: local
